### ISSUE TITLE
Final Choices/Questions flow

### ISSUE THREAD

**Issue by jalehman** [wdrury/social-remote#7]
@wdrury Are the questions always going to be hard-coded, or do we want to do something more intelligent? I can imagine doing a query for nearby yelp locations initially, and determining what kind of questions to ask based on the best (highest/most rated) choices. Is this something we want to try and accomplish?

**Comment by wdrury** [comment]
I think we should do hardcoded first, and try to get a decent level of polish before we add more features.

The questions:

* Are you Hungry/Thirsty?
  * Want to get a meal?
    * Quick and cheap?
      *  Terminal search: $ or $$ food
    * Sit down and dine?
      * Terminal search: $$$+ food
  * Want to get drinks?
    * Beer and music?
      * Terminal search: bar music
    * Wine and conversation?
      * Terminal search: wine bar
* Want to go do something?
  * See something cool?
    * By yourself in the dark?
      * Terminal search: theater
    * In the light with people?
      * Terminal search: art
  * Do something active?
    * Dancing?
      * Terminal search: dancing
    * Sports or Games?
      * Terminal search: bowling or darts
