### ISSUE TITLE
Final Question Images in Place

### ISSUE THREAD

**Issue by jalehman** [wdrury/social-remote#9]
I currently have the two questions of a choice represented by equal-width red and blue views -- this should obviously be made better.

**Comment by wdrury** [comment]
Yes, I would love the questions to be illustrated by what can be images of hot-looking people doing the activity.  They may have to be faded back slightly to make the text readable.  Not that the eye-searing red background isn't a great first cut ...

**Comment by wdrury** [comment]
I have some images in there, and the licensed version in my envato shopping cart.

**Comment by wdrury** [comment]
I think those are basically it.  We can always tweak more, but those images are licensed and sized and pretty good-looking.
